### ISSUE TITLE
YAML stream to JSON array

### ISSUE THREAD

**Issue by bryanlarsen** [bronze1man/yaml2json#19]
If you run yaml2json on a multi-document YAML file, the output is not valid JSON.   It'd be nice to have an option to output an array instead of a JSON stream.

Not a big deal, an easy workaround is to pipe it to `jq -s`

    foo | yaml2json | jq -s -r .

**Comment by bronze1man** [comment]
Please give a multi-document YAML file example that will cause the problem, so i can add a test as your case.
I do not know how to write a multi-document YAML file...

**Comment by dosmanak** [comment]
multidocument yaml file is delimited with `---`
```
---
a: hello
obj:
  nested:
    - 1
    - 2
---
anotheryaml:
  here: defined
```
